image:
  - Visual Studio 2017

configuration: Default

platform:
  - x64
  - Win32

before_build:
  - cmd: |
          git clone --depth 1 https://chromium.googlesource.com/external/gyp
          gyp\gyp rcedit.gyp --depth .

build:
  project: rcedit.sln
  parallel: true
  verbosity: minimal

branches:
  only:
    - master

artifacts:
  - path: Default\rcedit.exe
    name: rcedit-$(PLATFORM).exe

deploy:
  - provider: GitHub
    release: Rcedit $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '(placeholder)'
    auth_token:
      secure: XfjkG3WqHpNfpT3s2KB8h9LgGvSKqMvJGafkBWcwR2nCGPTQdPolH2Qb6T9WkpW5
    artifact: /.*\.exe/
    draft: true
    force_update: true
    prerelease: false
    on:
      appveyor_repo_tag: true
